" nimbuspad-plus-plus/src/vimrc

set number
set relativenumber
syntax on
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set mouse=a
let mapleader = " "

call plug#begin('~/.vim/plugged')
Plug 'preservim/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tomasiser/vim-code-dark'
Plug 'tpope/vim-fugitive'
call plug#end()

nnoremap <leader>e :NERDTreeToggle<CR>
let NERDTreeShowHidden=1

if !empty(globpath(&rtp, 'colors/codedark.vim'))
    colorscheme codedark
else
    colorscheme default
endif

highlight Normal guibg=#0A0E1A guifg=#B0BEC5
highlight LineNr guifg=#2A6DD1
highlight CursorLine guibg=#1A1B23
highlight Comment guifg=#A0A0A0
highlight String guifg=#FF00E5
highlight Function guifg=#00D4FF

set cursorline

nnoremap <leader>ff :find<Space>
nnoremap <leader>fs :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>w :w<CR>

command! OpenVSCode :call system('code . &')
nnoremap <leader>vc :OpenVSCode<CR>
